[platformio]

[env:native]
platform = native
build_flags =
	-std=c++17
	-Wno-comment
	-fno-pretty-templates
lib_deps=
	HAPI     =symlink://../../../../HAPI
	OneData  =symlink://../../../../OneData
	OneItem  =symlink://../../../../OneItem
	OneBit   =symlink://../../../../OneBit
	OneOutput=symlink://../../../../OneOutput
	OnePin   =symlink://../../../../OnePin
	OneChip  =symlink://../../../../OneChip
	OneMenu  =symlink://../../../../OneMenu

[env:uno]
board = uno
platform = atmelavr
framework = arduino
build_flags = -std=c++17
lib_deps=
	HAPI     =symlink://../../../../HAPI
	OneData  =symlink://../../../../OneData
	OneItem  =symlink://../../../../OneItem
	OneBit   =symlink://../../../../OneBit
	OneOutput=symlink://../../../../OneOutput
	OnePin   =symlink://../../../../OnePin
	OneChip  =symlink://../../../../OneChip
	OneMenu  =symlink://../../../../OneMenu

[env:lolin32]
board = lolin32
platform = espressif32
framework = arduino
build_flags = -std=gnu++17
lib_deps=
	HAPI     =symlink://../../../../HAPI
	OneData  =symlink://../../../../OneData
	OneItem  =symlink://../../../../OneItem
	OneBit   =symlink://../../../../OneBit
	OneOutput=symlink://../../../../OneOutput
	OnePin   =symlink://../../../../OnePin
	OneChip  =symlink://../../../../OneChip
	OneMenu  =symlink://../../../../OneMenu
	OneIO    =symlink://../../../../OneIO

[env:stm32f0]
board = bluepill_f103c8
platform = ststm32
framework = arduino
build_flags = -std=gnu++17
lib_deps=
	HAPI     =symlink://../../../../HAPI
	OneData  =symlink://../../../../OneData
	OneItem  =symlink://../../../../OneItem
	OneBit   =symlink://../../../../OneBit
	OneOutput=symlink://../../../../OneOutput
	OnePin   =symlink://../../../../OnePin
	OneChip  =symlink://../../../../OneChip
	OneMenu  =symlink://../../../../OneMenu
