[env:native]
platform = native
build_flags =
	-g
	-std=c++17
	-Wno-comment
	-fno-pretty-templates
debug_build_flags = -O0 -ggdb3 -g3 -no-pie
	-Wno-comment
	-fno-pretty-templates
lib_deps =
	HAPI      = https://github.com/InternetOfPins/HAPI.git
	OneBit    = https://github.com/InternetOfPins/OneBit.git
	OnePin    = https://github.com/InternetOfPins/OnePin.git
	OneBus    = https://github.com/InternetOfPins/OneBus.git
	OneChip   = https://github.com/InternetOfPins/OneChip.git
	OneData   = https://github.com/InternetOfPins/OneData.git
	OneOutput = https://github.com/InternetOfPins/OneOutput.git
	OneItem   = https://github.com/InternetOfPins/OneItem.git
	OneParse  = https://github.com/InternetOfPins/OneParse.git
	OneMenu   = https://github.com/InternetOfPins/OneMenu.git

[env:uno]
; platform = atmelavr
platform = atmelavr@^4.0.0
board = uno
framework = arduino
upload_port = /dev/ttyACM0
monitor_port = /dev/ttyACM0
monitor_speed = 115200
build_flags =
	-std=c++17
build_unflags =
	-std=c++11
	-std=c++14
	-std=c++20
	-std=c++2a
	-std=gnu++11
	-std=gnu++14
	-std=gnu++20
	-std=gnu++2a
	-std=gnu++1z
lib_deps =
	HAPI      = https://github.com/InternetOfPins/HAPI.git
	OneBit    = https://github.com/InternetOfPins/OneBit.git
	OnePin    = https://github.com/InternetOfPins/OnePin.git
	OneBus    = https://github.com/InternetOfPins/OneBus.git
	OneChip   = https://github.com/InternetOfPins/OneChip.git
	OneData   = https://github.com/InternetOfPins/OneData.git
	OneOutput = https://github.com/InternetOfPins/OneOutput.git
	OneItem   = https://github.com/InternetOfPins/OneItem.git
	OneParse  = https://github.com/InternetOfPins/OneParse.git
	OneMenu   = https://github.com/InternetOfPins/OneMenu.git
	https://github.com/neu-rah/streamFlow.git

[env:pico]
board = rpipico
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags =
	-std=gnu++17
build_unflags =
	-std=c++11
	-std=c++14
	-std=c++20
	-std=gnu++11
	-std=gnu++14
lib_deps =
	HAPI      = https://github.com/InternetOfPins/HAPI.git
	OneBit    = https://github.com/InternetOfPins/OneBit.git
	OnePin    = https://github.com/InternetOfPins/OnePin.git
	OneBus    = https://github.com/InternetOfPins/OneBus.git
	OneChip   = https://github.com/InternetOfPins/OneChip.git
	OneData   = https://github.com/InternetOfPins/OneData.git
	OneOutput = https://github.com/InternetOfPins/OneOutput.git
	OneItem   = https://github.com/InternetOfPins/OneItem.git
	OneParse  = https://github.com/InternetOfPins/OneParse.git
	OneMenu   = https://github.com/InternetOfPins/OneMenu.git
	https://github.com/neu-rah/tinyTimeUtils.git@^1.1.6

[env:pico2]
board = rpipico2
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
build_flags =
	-std=gnu++17
build_unflags =
	-std=c++11
	-std=c++14
	-std=c++20
	-std=gnu++11
	-std=gnu++14
lib_deps =
	HAPI      = https://github.com/InternetOfPins/HAPI.git
	OneBit    = https://github.com/InternetOfPins/OneBit.git
	OnePin    = https://github.com/InternetOfPins/OnePin.git
	OneBus    = https://github.com/InternetOfPins/OneBus.git
	OneChip   = https://github.com/InternetOfPins/OneChip.git
	OneData   = https://github.com/InternetOfPins/OneData.git
	OneOutput = https://github.com/InternetOfPins/OneOutput.git
	OneItem   = https://github.com/InternetOfPins/OneItem.git
	OneParse  = https://github.com/InternetOfPins/OneParse.git
	OneMenu   = https://github.com/InternetOfPins/OneMenu.git
	https://github.com/neu-rah/tinyTimeUtils.git@^1.1.6
